/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_test.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

#include "s21_string.h"

START_TEST(DIMON){
  char str[200] = "Hello my Litle Dog";
  char str2[200] = "Hello my Litle Dog";
  
  char* ac = s21_strtok(str," ");
  char* ex = strtok(str2," ");
  printf("--> %s --> %s\n",ac,ex);
  ck_assert_str_eq(ac,ex);

   ac = s21_strtok(NULL," ");
   ex = strtok(NULL," ");
  printf("--> %s --> %s\n",ac,ex);
  ck_assert_str_eq(ac,ex);

  ac = s21_strtok(NULL," ");
   ex = strtok(NULL," ");
  printf("--> %s --> %s\n",ac,ex);
  ck_assert_str_eq(ac,ex);

  ac = s21_strtok(NULL," ");
   ex = strtok(NULL," ");
  printf("--> %s --> %s\n",ac,ex);
  ck_assert_str_eq(ac,ex);

  ac = s21_strtok(NULL," ");
   ex = strtok(NULL," ");
  printf("--> %s --> %s\n",ac,ex);
  ck_assert_ptr_null(ac);
  ck_assert_ptr_null(ex);



}END_TEST

START_TEST(test_s21_memchr) {
#line 6
  //(const void *str, int c, size_t n)
  //Выполняет поиск первого вхождения символа c (беззнаковый тип) в
  //первых n байтах строки, на которую указывает аргумент str.
  fail_unless(s21_memchr("12345", '3', 4) == memchr("12345", '3', 4));
  fail_unless(s21_memchr("", 'u', 1) == memchr("", 'u', 1));
  fail_unless(s21_memchr("123", '\0', 10) == memchr("123", '\0', 10));

  int test_int = __INT_MAX__;
  void *resulting, *expected;

  resulting = s21_memchr(&test_int, 2, 4);
  expected = memchr(&test_int, 2, 4);

  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%d\", \"4\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
      test_int, expected, resulting);

  resulting = s21_memchr(&test_int, 255, 4);
  expected = memchr(&test_int, 255, 4);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%u\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
                test_int, 4, expected, resulting);

  test_int = 128 + 128 * 3;

  resulting = s21_memchr(&test_int, 128, 4);
  expected = memchr(&test_int, 128, 4);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%u\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
                test_int, 4, expected, resulting);
  test_int = 128 * 256 + 128 * 256 * 256;

  resulting = s21_memchr(&test_int, 128, 1);
  expected = memchr(&test_int, 128, 1);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%u\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
                test_int, 1, expected, resulting);
}
END_TEST

START_TEST(test_s21_memcmp) {
#line 41
  //(const void *str1, const void *str2, size_t n)
  //Сравнивает первые n байтов str1 и str2.
  fail_unless(s21_memcmp("12345", "12345", 3) == memcmp("12345", "12345", 3));
  fail_unless(s21_memcmp("aaaaa", "bbbb", 4) == memcmp("aaaaa", "bbbb", 4));
  fail_unless((s21_memcmp("aaaaa", "a3aaa", 4) < 0) ==
              (memcmp("aaaaa", "a3aaa", 4) < 0));
  fail_unless((s21_memcmp("a3aa", "aaaaa", 2) > 0) ==
              (memcmp("a3aaa", "aaaaa", 2) > 0));

  unsigned int test_int = (unsigned int)-1;
  unsigned int test_int2 = (unsigned int)__INT_MAX__;
  int resulting, expected = 0;

  resulting = s21_memcmp(&test_int, &test_int2, 4);
  expected = memcmp(&test_int, &test_int2, 4);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%d\")\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n",
                test_int, test_int2, expected, resulting);

  test_int2 = (unsigned int)-1;

  resulting = s21_memcmp(&test_int, &test_int2, 4);
  expected = memcmp(&test_int, &test_int2, 4);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%d\")\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n",
                test_int, test_int2, expected, resulting);

  test_int = 256 * 3;
  test_int2 = 256 * 2;

  resulting = s21_memcmp(&test_int, &test_int2, 1);
  expected = memcmp(&test_int, &test_int2, 1);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%d\")\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n",
                test_int, test_int2, expected, resulting);

  test_int = 256 * 256 * 25;
  test_int2 = 256 * 256 * 32;
  resulting = s21_memcmp(&test_int, &test_int2, 1);
  expected = memcmp(&test_int, &test_int2, 1);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%d\", "
                "\"%d\")\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n",
                test_int, test_int2, expected, resulting);
}
END_TEST

START_TEST(test_s21_strcmp) {
#line 85
  //(const char *str1, const char *str2)
  //Сравнивает строку, на которую указывает str1, со строкой,
  //на которую указывает str2.
  fail_unless(s21_strcmp("12345", "12345") == strcmp("12345", "12345"));
  fail_unless(s21_strcmp("12345", "aaaaa") != strcmp("12345", "12345"));
  fail_unless((s21_strcmp("12345", "1a") < 0) == (strcmp("12345", "1a") < 0));
  fail_unless((s21_strcmp("ab", "a2345") > 0) == (strcmp("ab", "a2345") > 0));
}
END_TEST

START_TEST(test_s21_memcpy) {
#line 95
  //(void *dest, const void *src, size_t n)
  //Копирует n символов из src в dest.
  char dest[100] = "bbbbbbbb";
  char s21_dest[100] = "bbbbbbbb";
  fail_unless(s21_strcmp(memcpy(dest, "qwerty", 3),
                         s21_memcpy(s21_dest, "qwerty", 3)) == 0);
  fail_unless(s21_strcmp(memcpy(dest, "qwerty", 1),
                         s21_memcpy(s21_dest, "qwerty", 1)) == 0);
  fail_unless(s21_strcmp(memcpy(dest, "qwerty", 0),
                         s21_memcpy(s21_dest, "qwerty", 0)) == 0);

  char test_str[] = "AMOGUS";
  char resulting[strlen(test_str) + 1];

  s21_memcpy(resulting, &test_str, strlen(test_str) + 1);
  ck_assert_msg(!strcmp(resulting, test_str),
                "\nINPUT_VALUE=(\"%s\", \"%ld\")\nRESULT_VALUE=(%s)\n",
                test_str, strlen(test_str) + 1, resulting);

  unsigned int test_int = (unsigned int)__INT_MAX__ * 2;
  unsigned int* result_int;
  result_int = (unsigned int*)malloc(sizeof(unsigned int));

  s21_memcpy(result_int, &test_int, sizeof(int));
  ck_assert_msg(*result_int == test_int,
                "\nINPUT_VALUE=(\"%u\", \"%ld\")\nRESULT_VALUE=(%s)\n",
                *result_int, sizeof(int), resulting);
  free(result_int);
}
END_TEST

START_TEST(test_s21_memmove) {
#line 120
  //(void *dest, const void *src, size_t n)
  // Еще одна функция для копирования n символов из src в dest.
  char arr[100] = "123456";
  char dest[100] = "bbbbbbbb";
  char s21_dest[100] = "bbbbbbbb";
  fail_unless(s21_strcmp(memmove(dest, &arr[3], 10),
                         s21_memmove(s21_dest, &arr[3], 10)) == 0);
  fail_unless(s21_strcmp(memmove(dest, &arr[1], 1),
                         s21_memmove(s21_dest, &arr[1], 1)) == 0);
  fail_unless(s21_strcmp(memmove(dest, "qwerty", 6),
                         s21_memmove(s21_dest, "qwerty", 6)) == 0);

  char test_str[] = "AMOGUS";
  char* resulting;
  resulting = malloc(sizeof(char) * (strlen(test_str) + 1));

  s21_memmove(resulting, &test_str, strlen(test_str) + 1);
  ck_assert_msg(!strcmp(resulting, test_str),
                "\nINPUT_VALUE=(\"%s\", \"%ld\")\nRESULT_VALUE=(%s)\n",
                test_str, strlen(test_str) + 1, resulting);
  free(resulting);

  unsigned int test_int = (unsigned int)__INT_MAX__ * 2;
  unsigned int* result_int;
  result_int = malloc(sizeof(int));

  s21_memmove(result_int, &test_int, sizeof(int));
  ck_assert_msg(*result_int == test_int,
                "\nINPUT_VALUE=(\"%u\", \"%ld\")\nRESULT_VALUE=(%u)\n",
                *result_int, sizeof(int), *result_int);
  free(result_int);

  s21_memmove(&test_str[1], &test_str, strlen(test_str) + 1);
  ck_assert_msg(!strcmp("AAMOGUS", test_str),
                "\nINPUT_VALUE=(\"%s\", \"%ld\")\nRESULT_VALUE=(%s)\n",
                test_str, strlen(test_str) + 1, test_str);
}
END_TEST

START_TEST(test_s21_memset) {
#line 153
  //(void *str, int c, size_t n)
  //Копирует символ c (беззнаковый тип) в первые n символов строки,
  //на которую указывает аргумент str.
  char dest[100] = "bbbbbbbb12345";
  char s21_dest[100] = "bbbbbbbb12345";
  fail_unless(
      s21_strcmp(memset(dest, '0', 10), s21_memset(s21_dest, '0', 10)) == 0);
  fail_unless(s21_strcmp(memset(dest + 5, '.', 8 * sizeof(char)),
                         s21_memset(s21_dest + 5, '.', 8 * sizeof(char))) == 0);
  fail_unless(s21_strcmp(memset(&dest[8], 'a', 5 * sizeof(char)),
                         s21_memset(&s21_dest[8], 'a', 5 * sizeof(char))) == 0);

  int test_int_res = 0;
  int test_int_orig = 0;

  s21_memset((void*)&test_int_res + 3, 128, 1);
  memset((void*)&test_int_orig + 3, 128, 1);

  ck_assert_msg(
      test_int_res == test_int_orig,
      "\nINPUT_VALUE=(%d, %d, %d)\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n", 0,
      128, 1, test_int_orig, test_int_res);

  test_int_res = 0;
  test_int_orig = 0;

  s21_memset(&test_int_res, 255, 3);
  memset(&test_int_orig, 255, 3);

  ck_assert_msg(
      test_int_res == test_int_orig,
      "\nINPUT_VALUE=(%d, %d, %d)\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n", 0,
      128, 1, test_int_orig, test_int_res);
}
END_TEST

START_TEST(test_s21_strcat) {
#line 181
  //(char *dest, const char *src)
  //Добавляет строку, на которую указывает src, в конец строки,
  //на которую указывает dest.
  char dest[100] = "bbbbbbbb";
  char s21_dest[100] = "bbbbbbbb";
  fail_unless(
      s21_strcmp(strcat(dest, "aboba"), s21_strcat(s21_dest, "aboba")) == 0);
  fail_unless(s21_strcmp(strcat(dest, ""), s21_strcat(s21_dest, "")) == 0);
  fail_unless(s21_strcmp(strcat(dest, "."), s21_strcat(s21_dest, ".")) == 0);

  char test_str[] = "AMOG";
  char second_str[] = "US";
  const char expected[] = "AMOGUS";
  char* resulting =
      (char*)malloc((strlen(test_str) + strlen(second_str) + 1) * sizeof(char));
  strcpy(resulting, test_str);

  resulting = s21_strcat(resulting, second_str);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                "AMOG", second_str, expected, resulting);

  char test_str_2[] = "";
  char second_str_2[] = "";
  const char expected_2[] = "";
  char* resulting_2 = (char*)calloc(
      strlen(test_str_2) + strlen(second_str_2) + 1, sizeof(char));
  strcpy(resulting, test_str_2);

  resulting_2 = s21_strcat(resulting_2, second_str_2);
  ck_assert_msg(!strcmp(resulting_2, expected_2),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                "", second_str_2, expected_2, resulting_2);
  free(resulting);
  free(resulting_2);
}
END_TEST

START_TEST(test_s21_strncat) {
#line 213
  //(char *dest, const char *src, size_t n)
  //Добавляет строку, на которую указывает src, в конец строки,
  //на которую указывает dest, длиной до n символов.
  char dest[100] = "bbbbbbbb";
  char s21_dest[100] = "bbbbbbbb";
  fail_unless(s21_strcmp(strncat(dest, "aboba", 3 * sizeof(char)),
                         s21_strncat(s21_dest, "aboba", 3 * sizeof(char))) ==
              0);
  fail_unless(s21_strcmp(strncat(dest, s21_dest, 1),
                         s21_strncat(s21_dest, s21_dest, 1)) == 0);
  fail_unless(s21_strcmp(strncat(dest, "", 5), s21_strncat(s21_dest, "", 5)) ==
              0);

  char test_str[] = "AMOG";
  char second_str[] = "US";
  const char expected[] = "AMOGU";
  char* resulting =
      (char*)malloc((strlen(test_str) + strlen(second_str) + 1) * sizeof(char));
  strcpy(resulting, test_str);

  resulting = s21_strncat(resulting, second_str, 1);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                "AMOG", second_str, expected, resulting);
  free(resulting);

  const char expected_2[] = "AMOG";
  char second_str_2[] = "";
  char* resulting_2 = (char*)malloc(
      (strlen(test_str) + strlen(second_str_2) + 1) * sizeof(char));
  strcpy(resulting_2, test_str);

  resulting_2 = s21_strncat(resulting_2, second_str_2, 1);
  ck_assert_msg(!strcmp(resulting_2, expected_2),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                "AMOG", second_str_2, expected_2, resulting_2);
  free(resulting_2);
}
END_TEST

START_TEST(test_s21_strchr) {
#line 244
  //(const char *str, int c)
  //Выполняет поиск первого вхождения символа c (беззнаковый тип) в строке,
  //на которую указывает аргумент str.
  char str[100] = "123456789";
  fail_unless(s21_strchr(str, '3') == strchr(str, '3'));
  fail_unless(s21_strchr(str, 'a') == NULL);
  fail_unless(*(s21_strchr(str, '9')) == *(strchr(str, '9')));
}
END_TEST

START_TEST(test_s21_strncmp) {
#line 255
  //(const char *str1, const char *str2, size_t n)
  //Сравнивает не более первых n байтов str1 и str2.
  fail_unless(s21_strncmp("12345", "12345", 5) == strncmp("12345", "12345", 5));
  fail_unless(s21_strncmp("12345", "aaaaa", 3 * sizeof(char)) !=
              strncmp("12345", "12345", 3 * sizeof(char)));
  fail_unless((s21_strncmp("12345", "1a", 2) < 0) ==
              (strncmp("12345", "1a", 2) < 0));
  fail_unless((s21_strncmp("ab", "a2345", 4) > 0) ==
              (strncmp("ab", "a2345", 4) > 0));
}
END_TEST

START_TEST(test_s21_strcpy) {
#line 263
  //(char *dest, const char *src)
  //Копирует строку, на которую указывает src, в dest.
  char dest[100] = "bbbbbbbb";
  char s21_dest[100] = "bbbbbbbb";
  fail_unless(s21_strcmp(strcpy(&dest[3], "aboba"),
                         s21_strcpy(&s21_dest[3], "aboba")) == 0);
  fail_unless(
      s21_strcmp(strcpy(dest, "aboba"), s21_strcpy(s21_dest, "aboba")) == 0);
  fail_unless(
      s21_strcmp(strcpy(&dest[4], "\0"), s21_strcpy(&s21_dest[4], "\0")) == 0);
}
END_TEST

START_TEST(test_s21_strncpy) {
#line 272
  //(char *dest, const char *src, size_t n)
  //Копирует до n символов из строки, на которую указывает src, в dest.
  char dest[100] = "bbbbbbbb";
  char s21_dest[100] = "bbbbbbbb";
  fail_unless(strcmp(strncpy(dest, "aboba", 10),
                     s21_strncpy(s21_dest, "aboba", 10)) == 0);
  fail_unless(strcmp(strncpy(&dest[4], "\0", 2),
                     s21_strncpy(&s21_dest[4], "\0", 2)) == 0);
}
END_TEST

START_TEST(test_strcspn) {
#line 283
  char test_str[] = "abcdefghijk";
  char test_s_arg[] = "c";
  unsigned long resulting, expected;

  resulting = s21_strcspn(test_str, test_s_arg);
  expected = strcspn(test_str, test_s_arg);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str, test_s_arg, expected, resulting);

  char test_str2[] = "abdefg";
  resulting = s21_strcspn(test_str2, test_s_arg);
  expected = strcspn(test_str2, test_s_arg);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str2, test_s_arg, expected, resulting);

  char test_str3[] = "";
  resulting = s21_strcspn(test_str3, test_s_arg);
  expected = strcspn(test_str3, test_s_arg);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str3, test_s_arg, expected, resulting);

  char test_s_arg2[] = "abcdefghijkasdf";
  resulting = s21_strcspn(test_str, test_s_arg2);
  expected = strcspn(test_str, test_s_arg2);
  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str, test_s_arg2, expected, resulting);
}
END_TEST

START_TEST(test_strerror) {
#line 314
  char *resulting, *expected;

  resulting = s21_strerror(1);
  expected = strerror(1);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                1, expected, resulting);

  resulting = s21_strerror(-1);
  expected = strerror(-1);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                1, expected, resulting);

  resulting = s21_strerror(109);
  expected = strerror(109);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                1, expected, resulting);

  resulting = s21_strerror(140);
  expected = strerror(140);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                1, expected, resulting);
}
END_TEST

START_TEST(test_strlen) {
#line 340
  char test_str[] = "abcdefghijk";
  unsigned long resulting, expected;

  resulting = s21_strlen(test_str);
  expected = strlen(test_str);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_VALUE=(%ld)\n",
      test_str, expected, resulting);

  char test_str2[] = "";
  resulting = s21_strlen(test_str2);
  expected = strlen(test_str2);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_VALUE=(%ld)\n",
      test_str2, expected, resulting);
}
END_TEST

START_TEST(test_strpbrk) {
#line 356
  char *expected, *resulting;
  char test_str[] = "abcdefghijk";
  char test_s_arg[] = "c";

  resulting = s21_strpbrk(test_str, test_s_arg);
  expected = strpbrk(test_str, test_s_arg);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_s_arg, expected, resulting);

  char test_s_arg2[] = "dec";
  resulting = s21_strpbrk(test_str, test_s_arg2);
  expected = strpbrk(test_str, test_s_arg2);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_s_arg2, expected, resulting);

  char test_s_arg3[] = "";
  resulting = s21_strpbrk(test_str, test_s_arg3);
  expected = strpbrk(test_str, test_s_arg3);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_s_arg3, expected, resulting);

  char test_s_arg4[] = "P";
  resulting = s21_strpbrk(test_str, test_s_arg4);
  expected = strpbrk(test_str, test_s_arg4);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_s_arg4, expected, resulting);
}
END_TEST

START_TEST(test_strrchr) {
#line 385
  char test_str[] = "abcdefgchijk";
  char test_s_arg[] = "c";
  char sym = 'c';
  char *resulting, *expected;

  resulting = s21_strrchr(test_str, sym);
  expected = strrchr(test_str, sym);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%c\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
      test_str, sym, resulting, expected);

  test_s_arg[0] = '!';
  resulting = s21_strrchr(test_str, *test_s_arg);
  expected = strrchr(test_str, *test_s_arg);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%c\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
      test_str, *test_s_arg, resulting, expected);

  char test_str2[] = {65, 129, 0};
  char test_s_arg2 = 129;
  resulting = s21_strrchr(test_str2, test_s_arg2);
  expected = strrchr(test_str2, test_s_arg2);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%c\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
      test_str2, test_s_arg2, resulting, expected);

  char test_str3[] = "";
  char test_s_arg3 = 'a';
  resulting = s21_strrchr(test_str3, test_s_arg3);
  expected = strrchr(test_str3, test_s_arg3);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%c\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
      test_str3, test_s_arg3, resulting, expected);

  resulting = s21_strrchr(test_str, test_s_arg3);
  expected = strrchr(test_str, test_s_arg3);
  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%c\")\nEXCEPTED_VALUE=(%p)\nRESULT_VALUE=(%p)\n",
      test_str, test_s_arg3, resulting, expected);
}
END_TEST

START_TEST(test_strspn) {
#line 420
  char test_str[] = "abcdefghijk";
  char test_s_arg[] = "c";
  unsigned long resulting, expected;

  resulting = s21_strspn(test_str, test_s_arg);
  expected = strspn(test_str, test_s_arg);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str, test_s_arg, expected, resulting);

  char test_str2[] = "abdefg";
  resulting = s21_strspn(test_str2, test_s_arg);
  expected = strspn(test_str2, test_s_arg);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str2, test_s_arg, expected, resulting);

  char test_str3[] = "";
  resulting = s21_strspn(test_str3, test_s_arg);
  expected = strspn(test_str3, test_s_arg);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str3, test_s_arg, expected, resulting);

  char test_s_arg2[] = "dc";
  resulting = s21_strspn(test_str, test_s_arg2);
  expected = strspn(test_str, test_s_arg2);

  ck_assert_msg(resulting == expected,
                "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%ld)\nRESULT_"
                "VALUE=(%ld)\n",
                test_str, test_s_arg2, expected, resulting);
}
END_TEST

START_TEST(test_strstr) {
#line 453
  char *resulting, *expected;
  char test_str[] = "abcdefghijk";
  char test_arg[] = "def";

  resulting = s21_strstr(test_str, test_arg);
  expected = strstr(test_str, test_arg);

  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_arg, expected, resulting);

  char test_arg2[] = "abo";

  resulting = s21_strstr(test_str, test_arg2);
  expected = strstr(test_str, test_arg2);

  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_arg2, expected, resulting);

  char test_arg3[] = "";

  resulting = s21_strstr(test_str, test_arg3);
  expected = strstr(test_str, test_arg3);

  ck_assert_msg(
      resulting == expected,
      "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, test_arg3, expected, resulting);
}
END_TEST

START_TEST(test_strtok) {
#line 480
  char *resulting, *expected;
  char test_str_r[] = "abc def gh ijk";
  char test_str_e[] = "abc def gh ijk";
  char test_arg[] = " ";

  expected = strtok(test_str_r, "_");
  resulting = s21_strtok(test_str_e, "_");

  while (resulting != NULL) {
    ck_assert_msg(!strcmp(resulting, expected),
                  "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_"
                  "VALUE=(%s)\n",
                  test_str_r, "_", expected, resulting);
    expected = strtok(NULL, "_");
    resulting = s21_strtok(NULL, "_");
  }

  char test_str_r2[] = "abc def gh ijk";
  char test_str_e2[] = "abc def gh ijk";

  expected = strtok(test_str_r2, test_arg);
  resulting = s21_strtok(test_str_e2, test_arg);

  while (resulting != NULL) {
    ck_assert_msg(!strcmp(resulting, expected),
                  "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_"
                  "VALUE=(%s)\n",
                  test_str_r2, test_arg, expected, resulting);
    expected = strtok(NULL, test_arg);
    resulting = s21_strtok(NULL, test_arg);
  }

  char test_str_r3[] = "abc def gh ijk";
  char test_str_e3[] = "abc def gh ijk";
  char test_arg2[] = "";

  expected = strtok(test_str_r3, test_arg2);
  resulting = s21_strtok(test_str_e3, test_arg2);

  while (resulting != NULL) {
    ck_assert_msg(!strcmp(resulting, expected),
                  "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_"
                  "VALUE=(%s)\n",
                  test_str_r3, test_arg2, expected, resulting);
    expected = strtok(NULL, test_arg2);
    resulting = s21_strtok(NULL, test_arg2);
  }

  char test_str_r4[] = "abc def gh ijk";
  char test_str_e4[] = "abc def gh ijk";
  char test_arg3[] = "bc j";
  expected = strtok(test_str_r4, test_arg3);
  resulting = s21_strtok(test_str_e4, test_arg3);
  int i = 1;
  while (resulting != NULL) {
    ck_assert_msg(!strcmp(resulting, expected),
                  "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_"
                  "VALUE=(%s)\n",
                  test_str_e4, test_arg3, expected, resulting);
    expected = strtok(NULL, test_arg3);
    resulting = s21_strtok(NULL, test_arg3);
    i++;
  }

  char test_str_r5[] = "abc def gh ijk";
  char test_str_e5[] = "abc def gh ijk";
  char test_arg4[] = "bej";

  expected = strtok(test_str_r5, test_arg4);
  resulting = s21_strtok(test_str_e5, test_arg4);

  while (resulting != NULL) {
    ck_assert_msg(!strcmp(resulting, expected),
                  "\nINPUT_VALUE=(\"%s\",\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_"
                  "VALUE=(%s)\n",
                  test_str_r5, test_arg4, expected, resulting);
    expected = strtok(NULL, test_arg4);
    resulting = s21_strtok(NULL, test_arg4);
  }
}
END_TEST

START_TEST(test_to_upper) {
#line 551
  char test_str[] = "AbObAasdfnLKNFLasdf";
  char expected[] = "ABOBAASDFNLKNFLASDF";
  char* resulting;

  resulting = s21_to_upper(test_str);

  ck_assert_msg(
      !strcmp(resulting, expected),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, expected, resulting);

  char test_str2[] = "";
  char expected2[] = "";

  resulting = s21_to_upper(test_str2);

  ck_assert_msg(
      !strcmp(resulting, expected2),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str2, expected2, resulting);

  char test_str3[] = "0123456789";
  char expected3[] = "0123456789";

  resulting = s21_to_upper(test_str3);

  ck_assert_msg(
      !strcmp(resulting, expected3),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=  (%s)\n",
      test_str3, expected3, resulting);

  char test_str4[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`"
      "abcdefghijklmnopqrstuvwxyz{|}~";
  char expected4d[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`"
      "ABCDEFGHIJKLMNOPQRSTUVWXYZ{|}~";

  resulting = s21_to_upper(test_str4);

  ck_assert_msg(
      !strcmp(resulting, expected4d),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str4, expected4d, resulting);
}
END_TEST

START_TEST(test_to_lower) {
#line 588
  char test_str[] = "AbObAasdfnLKNFLasdf";
  char expected[] = "abobaasdfnlknflasdf";
  char* resulting;

  resulting = s21_to_lower(test_str);

  ck_assert_msg(
      !strcmp(resulting, expected),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str, expected, resulting);

  char test_str2[] = "";
  char expected2[] = "";

  resulting = s21_to_lower(test_str2);

  ck_assert_msg(
      !strcmp(resulting, expected2),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str2, expected2, resulting);

  char test_str3[] = "0123456789";
  char expected3[] = "0123456789";

  resulting = s21_to_lower(test_str3);

  ck_assert_msg(
      !strcmp(resulting, expected3),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str3, expected3, resulting);

  char test_str4[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`"
      "abcdefghijklmnopqrstuvwxyz{|}~";
  char expected4[] =
      " !\"#$%&'()*+,-./"
      "0123456789:;<=>?@abcdefghijklmnopqrstuvwxyz[\\]^_`"
      "abcdefghijklmnopqrstuvwxyz{|}~";

  resulting = s21_to_lower(test_str4);

  ck_assert_msg(
      !strcmp(resulting, expected4),
      "\nINPUT_VALUE=(\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      test_str4, expected4, resulting);
}
END_TEST

START_TEST(test_insert) {
#line 626
  char* resulting;
  int index;

  char test_str[] = "AMOG";
  char test_s_arg[] = "us";
  char expected[] = "AMOGus";
  index = 4;

  resulting = s21_insert(test_str, test_s_arg, index);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg, index, expected, resulting);

  char expected2[] = "usAMOG";
  index = 0;

  resulting = s21_insert(test_str, test_s_arg, index);
  ck_assert_msg(!strcmp(resulting, expected2),
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg, index, expected2, resulting);

  char test_2[] = "aaabbb";
  resulting = s21_insert(test_2, " ", 3);
  ck_assert_msg(!strcmp(resulting, "aaa bbb"),
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg, index, "aaa bbb", resulting);

  resulting = s21_insert(test_2, " ", 6);
  ck_assert_msg(!strcmp(resulting, "aaabbb "),
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg, index, "aaabbb ", resulting);

  char test_s_arg2[] = "SUUUUUUUUUUUUUUUI";
  char expected3[] = "AMSUUUUUUUUUUUUUUUIOG";
  index = 2;

  resulting = s21_insert(test_str, test_s_arg2, index);
  ck_assert_msg(!strcmp(resulting, expected3),
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg2, index, expected3, resulting);

  char test_s_arg3[] = "";
  char expected4[] = "AMOG";
  index = 2;

  resulting = s21_insert(test_str, test_s_arg3, index);
  ck_assert_msg(!strcmp(resulting, expected4),
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg3, index, expected4, resulting);

  index = 10;

  resulting = s21_insert(test_str, test_s_arg3, index);
  ck_assert_msg(resulting == s21_NULL,
                "\nINPUT_VALUE=(\"%s\",\"%s\", "
                "%d)\nEXCEPTED_VALUE=(NULL)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg3, index, resulting);
}
END_TEST

START_TEST(test_trim) {
#line 685
  char* resulting;
  char test_str[] = "*** Much Ado About Nothing ***";
  char test_s_arg[] = "* \\";
  char expected[] = "Much Ado About Nothing";

  resulting = s21_trim(test_str, test_s_arg);
  ck_assert_msg(!strcmp(resulting, expected),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg, expected, resulting);

  char test_s_arg2[] = "";

  resulting = s21_trim(test_str, test_s_arg2);

  ck_assert_msg(!strcmp(resulting, test_str),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str, test_s_arg2, test_str, resulting);

  char test_str2[] = "***  ***";
  resulting = s21_trim(test_str2, test_s_arg);

  ck_assert_msg(resulting == s21_NULL,
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(NULL)\nRESULT_VALUE=(%s)\n",
                test_str2, test_s_arg, resulting);

  char test_str3[] = "";
  resulting = s21_trim(test_str3, test_s_arg);

  ck_assert_msg(!strcmp(resulting, ""),
                "\nINPUT_VALUE=(\"%s\", "
                "\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                test_str3, test_s_arg2, "", resulting);

  //========================================================================
  //========================================================================
  //----------------------------------------------------------------------------------------------------------------------------------------
  // tests s21_sscanf
}
END_TEST

START_TEST(test_s21_sscanf_spec_d) {
#line 719
  //считываем из строки знаковое десятичное целое число
  int a = 0;
  int b = 1;
  char c = 'x';
  char c1 = 'y';
  short int ha = 0;
  short int hb = 1;
  long long int la = 0;
  long int lb = 1;
  fail_unless(s21_sscanf("   123xsd", "%d", &a) ==
              sscanf("   123xsd", "%d", &b));
  fail_unless(a == b);

  fail_unless(s21_sscanf("   123xsd", "%d", &a) ==
              sscanf("   123xsd", "%d", &b));
  fail_unless(a == b);

  fail_unless(s21_sscanf("000000001", "%d", &a) ==
              sscanf("000000001", "%d", &b));
  fail_unless(a == b);

  fail_unless(s21_sscanf("-5", "%d", &a) == sscanf("-5", "%d", &b));
  fail_unless(a == b);

  fail_unless(s21_sscanf("  +55555", "%d", &a) == sscanf("  +55555", "%d", &b));
  fail_unless(a == b);

  fail_unless(s21_sscanf("123456789", "%hd", &ha) ==
              sscanf("123456789", "%hd", &hb));  // test short
  fail_unless(ha == hb);

  fail_unless(s21_sscanf("9223372036854775807", "%ld", &la) ==
              sscanf("9223372036854775807", "%ld", &lb));  // test long
  fail_unless(la == lb);

  fail_unless(s21_sscanf("  -12345a", "%*d%c", &c) ==
              sscanf("  -12345a", "%*d%c", &c1));  // test *
  fail_unless(c == c1);

  fail_unless(s21_sscanf("111111111111111111111111111111a", "%d%c", &a, &c) ==
              sscanf("111111111111111111111111111111a", "%d%c", &b, &c1));
  fail_unless(c == c1);
  fail_unless(a == b);

  fail_unless(s21_sscanf("a1", "%d", &a) ==
              sscanf("a1", "%d", &b));  // test error

  fail_unless(s21_sscanf("", "%d", &a) ==
              sscanf("", "%d", &b));  // test error (return -1)

  fail_unless(s21_sscanf("123", "%r", &a) == 0);  // test error (default)
}
END_TEST

START_TEST(test_s21_sscanf_spec_c) {
#line 763
  //считываем из строки символ
  char c = 'x';
  char c1 = 'y';
  fail_unless(s21_sscanf("a", "%c", &c) == sscanf("a", "%c", &c1));
  fail_unless(c == c1);

  fail_unless(s21_sscanf("!!!!!!!", "%c", &c) == sscanf("!!!!!!!", "%c", &c1));
  fail_unless(c == c1);

  fail_unless(s21_sscanf(" ", "%c", &c) == sscanf(" ", "%c", &c1));
  fail_unless(c == c1);

  fail_unless(s21_sscanf("**", "%*c%c", &c) ==
              sscanf("**", "%*c%c", &c1));  // test *
  fail_unless(c == c1);
}
END_TEST

START_TEST(test_s21_sscanf_spec_s) {
#line 779
  //считываем из строки строку
  char str1[100];
  char str2[100];
  char str3[100];
  char str4[100];
  fail_unless(s21_sscanf("aboba", "%s", str1) == sscanf("aboba", "%s", str2));
  fail_unless(s21_strcmp(str1, str2) == 0);

  fail_unless(s21_sscanf("    aboba", "%s", str1) ==
              sscanf("     aboba", "%s", str2));  // test with spaces
  fail_unless(s21_strcmp(str1, str2) == 0);

  fail_unless(s21_sscanf("aboba    amogus", "%s%s", str1, str3) ==
              sscanf("aboba    amogus", "%s%s", str2, str4));
  fail_unless(s21_strcmp(str1, str2) == 0);
  fail_unless(s21_strcmp(str3, str4) == 0);

  fail_unless(s21_sscanf("  abo  ba", "%*s%s", str1) ==
              sscanf("  abo  ba", "%*s%s", str2));  // test *
  fail_unless(s21_strcmp(str1, str2) == 0);

  fail_unless(s21_sscanf("aboba11111111111", "%2s", str1) ==
              sscanf("aboba11111111111", "%2s", str2));  // tests with width
  fail_unless(s21_strcmp(str1, str2) == 0);
}
END_TEST

START_TEST(test_s21_sscanf_spec_i) {
#line 801
  //считываем из строки знаковое целое число (может быть десятичным,
  //восьмеричным или шестнадцатеричным)
  int a = 0;
  int b = 1;
  short int h1 = 0;
  short int h2 = 1;
  long long int l1 = 0;
  long int l2 = 1;
  fail_unless(s21_sscanf("10", "%i", &a) ==
              sscanf("10", "%i", &b));  // test in decimal
  fail_unless(a == b);

  fail_unless(s21_sscanf("0000123", "%i", &a) ==
              sscanf("0000123", "%i", &b));  // test in octal
  fail_unless(a == b);

  fail_unless(s21_sscanf("0x1f", "%i", &a) ==
              sscanf("0x1f", "%i", &b));  // test in hex
  fail_unless(a == b);

  fail_unless(s21_sscanf("-0xaaa", "%i", &a) ==
              sscanf("-0xaaa", "%i", &b));  // test negative
  fail_unless(a == b);

  fail_unless(s21_sscanf("    0xaaa123", "%i", &a) ==
              sscanf("    0xaaa123", "%i", &b));  // test with spaces
  fail_unless(a == b);

  fail_unless(
      s21_sscanf("    -0000000xbaaa", "%i", &a) ==
      sscanf("    -0000000xbaaa", "%i", &b));  // test with spaces and zeros
  fail_unless(a == b);

  fail_unless(s21_sscanf("   !   -0123", "%i", &a) ==
              sscanf("   !   -0123", "%i", &b));  // test error
  fail_unless(a == b);

  fail_unless(s21_sscanf("1234567", "%hi", &h1) ==
              sscanf("1234567", "%hi", &h2));  // test short with decimal
  fail_unless(h1 == h2);

  fail_unless(
      s21_sscanf("-9223372036854775807", "%li", &l1) ==
      sscanf("-9223372036854775807", "%li", &l2));  // test long with decimal
  fail_unless(l1 == l2);

  fail_unless(s21_sscanf("0111111", "%hi", &h1) ==
              sscanf("0111111", "%hi", &h2));  // test short with octal
  fail_unless(h1 == h2);

  fail_unless(
      s21_sscanf("077777777777777777", "%li", &l1) ==
      sscanf("077777777777777777", "%li", &l2));  // test long with octal
  fail_unless(l1 == l2);

  fail_unless(s21_sscanf("-0x", "%hi", &h1) ==
              sscanf("-0x", "%hi", &h2));  // test short with hex
  fail_unless(h1 == h2);

  fail_unless(s21_sscanf("0XFFFFFFFFFFFFFF", "%li", &l1) ==
              sscanf("0XFFFFFFFFFFFFFF", "%li", &l2));  // test long with hex
  fail_unless(l1 == l2);
}
END_TEST

START_TEST(test_s21_sscanf_spec_eEfgG) {
#line 848
  //считываем из строки десятичное число с плавающей точкой или научная нотация
  //(мантисса/экспонента)
  float d1, d2;
  long double ld1, ld2;
  char str1[100];
  char str2[100];
  fail_unless(s21_sscanf("0.12345", "%e", &d1) ==
              sscanf("0.12345", "%e", &d2));  // test double
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("50E3", "%e", &d1) ==
              sscanf("50E3", "%e", &d2));  // test double
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("-0.5e-10", "%e", &d1) ==
              sscanf("-0.5e-10", "%e", &d2));  // test double
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("1,7E300", "%Le", &ld1) ==
              sscanf("1,7E300", "%Le", &ld2));  // test long double
  fail_unless(ld1 == ld2);

  fail_unless(s21_sscanf("abc", "%e", &d1) ==
              sscanf("abc", "%e", &d2));  // test error
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("0.1      abc", "%*e%s", str1) ==
              sscanf("0.1      abc", "%*e%s", str2));  // test with *
  fail_unless(s21_strcmp(str1, str2) == 0);
}
END_TEST

START_TEST(test_s21_sscanf_spec_ouxX) {
#line 872
  //считываем из строки беззнаковое восьмеричное число/беззнаковое десятичное
  //целое число/беззнаковое шестнадцатеричное целое число
  unsigned int d1 = 0;
  unsigned int d2 = 1;
  unsigned short int hd1 = 0;
  unsigned short int hd2 = 1;
  unsigned long long int ld1 = 0;
  unsigned long int ld2 = 1;
  char c1 = 'x';
  char c2 = 'y';
  fail_unless(s21_sscanf("12345", "%u", &d1) ==
              sscanf("12345", "%u", &d2));  // test in decimal
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("0671", "%o", &d1) ==
              sscanf("0671", "%o", &d2));  // test in octal
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("-0xabcF1", "%x", &d1) ==
              sscanf("-0xabcF1", "%x", &d2));  // test in hex
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf(" \t 0000X0B", "%X", &d1) ==
              sscanf(" \t 0000X0B", "%X", &d2));  // test in hex
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("    -1", "%hu", &hd1) ==
              sscanf("     -1", "%hu", &hd2));  // test in decimal with short
  fail_unless(hd1 == hd2);

  fail_unless(s21_sscanf("42949672951111111111", "%lu", &ld1) ==
              sscanf("42949672951111111111", "%lu",
                     &ld2));  // test in decimal with long
  fail_unless(ld1 == ld2);

  fail_unless(s21_sscanf("0", "%ho", &hd1) ==
              sscanf("0", "%ho", &hd2));  // test in octal with short
  fail_unless(hd1 == hd2);

  fail_unless(s21_sscanf("7777777777777777777777777777777777", "%lo", &ld1) ==
              sscanf("7777777777777777777777777777777777", "%lo",
                     &ld2));  // test in octal with long
  fail_unless(ld1 == ld2);

  fail_unless(s21_sscanf("-000000xa", "%hx", &hd1) ==
              sscanf("-000000xa", "%hx", &hd2));  // test in hex with short
  fail_unless(hd1 == hd2);

  fail_unless(
      s21_sscanf("FFFFFfffffffffabcde", "%lx", &ld1) ==
      sscanf("FFFFFfffffffffabcde", "%lx", &ld2));  // test in hex with long
  fail_unless(ld1 == ld2);
  //тесты для *
  fail_unless(s21_sscanf("0a", "%*u%c", &c1) ==
              sscanf("0a", "%*u%c", &c2));  // test in decimal
  fail_unless(c1 == c2);

  fail_unless(s21_sscanf("671!", "%*o%c", &c1) ==
              sscanf("671!", "%*o%c", &c2));  // test in octal
  fail_unless(c1 == c2);

  fail_unless(s21_sscanf("-0xabcF1 ", "%*x%c", &c1) ==
              sscanf("-0xabcF1 ", "%*x%c", &c2));  // test in hex
  fail_unless(c1 == c2);

  fail_unless(s21_sscanf("*", "%*X%c", &c1) ==
              sscanf("*", "%*X%c", &c2));  // test in hex
  fail_unless(c1 == c2);

  fail_unless(s21_sscanf("aboba", "%u", &d1) ==
              sscanf("aboba", "%u", &d2));  // test error
}
END_TEST

START_TEST(test_s21_sscanf_spec_p) {
#line 926
  //считываем из строки адрес указателя
  int p1, p2;
  void* pp1 = &p1;
  void* pp2 = &p2;
  char c1, c2;
  fail_unless(s21_sscanf("10c", "%p", &pp1) == sscanf("10c", "%p", &pp2));
  ck_assert_ptr_eq(pp1, pp2);

  fail_unless(s21_sscanf("0x12345", "%p", &pp1) ==
              sscanf("0x12345", "%p", &pp2));
  ck_assert_ptr_eq(pp1, pp2);

  fail_unless(s21_sscanf("     0x1f", "%p", &pp1) ==
              sscanf("    0x1f", "%p", &pp2));
  ck_assert_ptr_eq(pp1, pp2);

  fail_unless(s21_sscanf("xxx.", "%p%c", &pp1, &c1) ==
              sscanf("xxx.", "%p%c", &pp2, &c2));  // test error

  fail_unless(s21_sscanf("!!!", "%*p%c", &c1) ==
              sscanf("!!!", "%*p%c", &c2));  // test with *
  fail_unless(c1 == c2);
}
END_TEST

START_TEST(test_s21_sscanf_spec_n) {
#line 946
  //записываем количество символов, считанных до появления %n
  int d1 = 0;
  int d2 = 1;
  int a = 0;
  int b = 1;
  char str1[100];
  char str2[100];
  fail_unless(s21_sscanf("   123xsd", "%d%s%n", &a, str1, &d1) ==
              sscanf("   123xsd", "%d%s%n", &b, str2, &d2));
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("+00000000000 qwerty !!", "%d%s%n", &a, str1, &d1) ==
              sscanf("+00000000000 qwerty !!", "%d%s%n", &b, str2, &d2));
  fail_unless(d1 == d2);
  fail_unless(s21_strcmp(str1, str2) == 0);

  fail_unless(s21_sscanf("00000000000 qwerty !!", "%*d%s%n", str1, &d1) ==
              sscanf("00000000000 qwerty !!", "%*d%s%n", str2, &d2));
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("7777777777777777777777777777777777", "%*o%n", &d1) ==
              sscanf("7777777777777777777777777777777777", "%*o%n", &d2));
  fail_unless(d1 == d2);
}
END_TEST

START_TEST(test_s21_sscanf_spec_percent) {
#line 967
  // считываем % из строки и пропускаем его
  int d1 = 0;
  int d2 = 1;
  int a = 0;
  int b = 1;
  char str1[100];
  char str2[100];
  fail_unless(s21_sscanf("% \t  1aboba", "%%%d%s%n", &a, str1, &d1) ==
              sscanf("% \t  1aboba", "%%%d%s%n", &b, str2, &d2));
  fail_unless(a == b);
  fail_unless(s21_strcmp(str1, str2) == 0);
  fail_unless(d1 == d2);

  fail_unless(s21_sscanf("qwerty\n", "%%%d%s%n", &a, str1, &d1) ==
              sscanf("qwerty\n", "%%%d%s%n", &b, str2, &d2));  // test error

  fail_unless(s21_sscanf(" % 5qwerty", "%%%d%s", &a, str1) ==
              sscanf(" % 5qwerty", "%%%d%s", &b, str2));  // test error
}
END_TEST

START_TEST(test_s21_sscanf_spec_combination) {
#line 984
  // тесты различных комбинаций спецификаторов
  int x1 = 0;
  int x2 = 1;
  char str1[100];
  char str2[100];
  char str3[100];
  char str4[100];
  float f1, f2;
  unsigned int d1 = 0;
  unsigned int d2 = 1;
  char c1, c2;
  fail_unless(
      s21_sscanf("\tqwerty   555 00000.1111111", "%s%d%g", str1, &x1, &f1) ==
      sscanf("\tqwerty   555 00000.1111111", "%s%d%g", str2, &x2, &f2));
  fail_unless(s21_strcmp(str1, str2) == 0);
  fail_unless(x1 == x2);
  fail_unless(f1 == f2);

  fail_unless(s21_sscanf("#0.2041e-15   -555 00000asdfg", "%c%f%u%7s", &c1, &f1,
                         &x1, str1) == sscanf("#0.2041e-15   -555 00000asdfg",
                                              "%c%f%u%7s", &c2, &f2, &x2,
                                              str2));
  fail_unless(c1 == c2);
  fail_unless(f1 == f2);
  fail_unless(x1 == x2);
  fail_unless(s21_strcmp(str1, str2) == 0);

  fail_unless(s21_sscanf("   aboba 123amogus0x1f -0xabcF1! 1.111@@",
                         "%s%s%x%c%G", str1, str2, &d1, &c1, &f1) ==
              sscanf("   aboba 123amogus0x1f -0xabcF1! 1.111@@", "%s%s%x%c%G",
                     str3, str4, &d2, &c2, &f2));
  fail_unless(s21_strcmp(str1, str3) == 0);
  fail_unless(s21_strcmp(str2, str4) == 0);
  fail_unless(d1 == d2);
  fail_unless(c1 == c2);
  fail_unless(f1 == f2);

  //----------------------------------------------------------------------------------------------------------------------------------------
}
END_TEST

void enter_specification(char* specification_str, char* current_format,
                         char* test_type) {
  memset(specification_str, 0, 100);
  strcpy(specification_str, "%%");
  strcpy(specification_str + 1, current_format);
  strcpy(specification_str + strlen(specification_str), test_type);
}

void check_and_print(int* num_of_current_test, char* name_spec,
                     char* specification_str, char* exp_buf, char* res_buf) {
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#%d: %s "
                "(format=\"%s\")\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                *num_of_current_test, name_spec, specification_str, exp_buf,
                res_buf);
  *num_of_current_test += 1;
}

void test_float(char* current_format, char* name_spec, int* test_start_num) {
  float test_float, big_fl, any_float;
  test_float = 3.256;
  big_fl = 3.4028e+30f;
  any_float = -129e-10f;
  char* res_buf = calloc(60, sizeof(char));
  char* exp_buf = calloc(60, sizeof(char));

  s21_sprintf(res_buf, current_format, 1.1f);
  sprintf(exp_buf, current_format, 1.1f);
  check_and_print(test_start_num, name_spec, current_format, exp_buf, res_buf);

  memset(res_buf, 0, 60);
  s21_sprintf(res_buf, current_format, any_float);
  sprintf(exp_buf, current_format, any_float);
  check_and_print(test_start_num, name_spec, current_format, exp_buf, res_buf);

  memset(res_buf, 0, 60);
  s21_sprintf(res_buf, current_format, test_float);
  sprintf(exp_buf, current_format, test_float);
  check_and_print(test_start_num, name_spec, current_format, exp_buf, res_buf);

  memset(res_buf, 0, 60);
  s21_sprintf(res_buf, current_format, big_fl);
  sprintf(exp_buf, current_format, big_fl);
  check_and_print(test_start_num, name_spec, current_format, exp_buf, res_buf);

  s21_sprintf(res_buf, current_format, 12.23);
  sprintf(exp_buf, current_format, 12.23);
  check_and_print(test_start_num, name_spec, current_format, exp_buf, res_buf);

  s21_sprintf(res_buf, current_format, 1. / 3.);
  sprintf(exp_buf, current_format, 1. / 3.);
  check_and_print(test_start_num, name_spec, current_format, exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}

/// @brief
/// @param current_format - without specification
/// @param name_spec - Name of specifcation
/// @param test_start_num - Start of counts for the sequence number of the test
void for_flag_specification(char* current_format, char* name_spec,
                            int* test_start_num) {
  char* test_str = calloc(100, sizeof(char));
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));
  char* specification_str = calloc(100, sizeof(char));
  strcpy(test_str, "adsfsadfas");

  enter_specification(specification_str, current_format, "c");
  s21_sprintf(res_buf, specification_str, 'A');
  sprintf(exp_buf, specification_str, 'A');
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  char* test_1[] = {"d", "i", "o", "u", "x", "X"};
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, 12);
    sprintf(exp_buf, specification_str, 12);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, -1);
    sprintf(exp_buf, specification_str, -1);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);
  }

  char* test_2[] = {"e", "E", "f", "g", "G"};
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, 123.23e-10);
    sprintf(exp_buf, specification_str, 123.23e-10);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, -123.23e+10);
    sprintf(exp_buf, specification_str, -123.23e+10);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, 0.0);
    sprintf(exp_buf, specification_str, 0.0);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, 1. / 3.);
    sprintf(exp_buf, specification_str, 1. / 3.);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);
  }

  enter_specification(specification_str, current_format, "s");
  s21_sprintf(res_buf, specification_str, "amogus");
  sprintf(exp_buf, specification_str, "amogus");
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  enter_specification(specification_str, current_format, "u");
  s21_sprintf(res_buf, specification_str, 213);
  sprintf(exp_buf, specification_str, 213);
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  enter_specification(specification_str, current_format, "p");
  s21_sprintf(res_buf, specification_str, test_str);
  sprintf(exp_buf, specification_str, test_str);
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  enter_specification(specification_str, current_format, "%");
  s21_sprintf(res_buf, specification_str);
  sprintf(exp_buf, specification_str);
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  free(res_buf);
  free(exp_buf);
  free(test_str);
  free(specification_str);
}

void for_flag_specification_wtih_star(char* current_format, char* name_spec,
                                      int* test_start_num, int star) {
  char* test_str = calloc(100, sizeof(char));
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));
  char* specification_str = calloc(100, sizeof(char));
  strcpy(test_str, "adsfsadfas");

  enter_specification(specification_str, current_format, "c");
  s21_sprintf(res_buf, specification_str, star, 'A');
  sprintf(exp_buf, specification_str, star, 'A');
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  char* test_1[] = {"d", "i", "o", "u", "x", "X"};
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, star, 12);
    sprintf(exp_buf, specification_str, star, 12);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, star, -1);
    sprintf(exp_buf, specification_str, star, -1);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);
  }

  char* test_2[] = {"e", "E", "f", "g", "G"};
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, star, 123.23e-10);
    sprintf(exp_buf, specification_str, star, 123.23e-10);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, star, -123.23e+10);
    sprintf(exp_buf, specification_str, star, -123.23e+10);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, star, 0.0);
    sprintf(exp_buf, specification_str, star, 0.0);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, star, 1. / 3.);
    sprintf(exp_buf, specification_str, star, 1. / 3.);
    check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                    res_buf);
  }

  enter_specification(specification_str, current_format, "s");
  s21_sprintf(res_buf, specification_str, star, "amogus");
  sprintf(exp_buf, specification_str, star, "amogus");
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  enter_specification(specification_str, current_format, "u");
  s21_sprintf(res_buf, specification_str, star, 213);
  sprintf(exp_buf, specification_str, star, 213);
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  enter_specification(specification_str, current_format, "p");
  s21_sprintf(res_buf, specification_str, star, test_str);
  sprintf(exp_buf, specification_str, star, test_str);
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  enter_specification(specification_str, current_format, "%");
  s21_sprintf(res_buf, specification_str);
  sprintf(exp_buf, specification_str);
  check_and_print(test_start_num, name_spec, specification_str, exp_buf,
                  res_buf);

  free(res_buf);
  free(exp_buf);
  free(test_str);
  free(specification_str);
}

//
// ======= TEST SPECIFICATION ======
//

START_TEST(test_spec_c) {
  int test_int;
  test_int = 100;
  char test_chr;
  test_chr = ' ';
  char* res_buf = calloc(10, sizeof(char));
  char* exp_buf = calloc(10, sizeof(char));

  s21_sprintf(res_buf, "%c", test_int);
  sprintf(exp_buf, "%c", test_int);
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#1: specification "
                "\"%%c\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  s21_sprintf(res_buf, "%c", test_chr);
  sprintf(exp_buf, "%c", test_chr);

  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#2: specification "
                "\"%%c\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  s21_sprintf(res_buf, "%c", 'c');
  sprintf(exp_buf, "%c", 'c');
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#3: specification "
                "\"%%c\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_d) {
  int test_start_num;
  int big_int, min_int, test_int;
  big_int = INT32_MAX;
  min_int = INT32_MIN;
  test_int = 100;
  test_start_num = 1;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%d", test_int);
  sprintf(exp_buf, "%d", test_int);
  check_and_print(&test_start_num, "Spec %d", "%d", exp_buf, res_buf);

  s21_sprintf(res_buf, "%d", big_int);
  sprintf(exp_buf, "%d", big_int);
  check_and_print(&test_start_num, "Spec %d", "%d", exp_buf, res_buf);
  ;

  s21_sprintf(res_buf, "%d", min_int);
  sprintf(exp_buf, "%d", min_int);
  check_and_print(&test_start_num, "Spec %d", "%d", exp_buf, res_buf);

  s21_sprintf(res_buf, "%d", 12);
  sprintf(exp_buf, "%d", 12);
  check_and_print(&test_start_num, "Spec %d", "%d", exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_i) {
  int test_int, big_int, min_int, hex_num;
  big_int = INT32_MAX;
  min_int = INT32_MIN;
  test_int = 100;
  int test_start_num = 1;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%i", test_int);
  sprintf(exp_buf, "%i", test_int);
  check_and_print(&test_start_num, "Spec %i", "%i", exp_buf, res_buf);

  s21_sprintf(res_buf, "%i", big_int);
  sprintf(exp_buf, "%i", big_int);
  check_and_print(&test_start_num, "Spec %i", "%i", exp_buf, res_buf);

  s21_sprintf(res_buf, "%i", min_int);
  sprintf(exp_buf, "%i", min_int);
  check_and_print(&test_start_num, "Spec %i", "%i", exp_buf, res_buf);

  hex_num = 0xfa;
  s21_sprintf(res_buf, "%i", hex_num);
  sprintf(exp_buf, "%i", hex_num);
  check_and_print(&test_start_num, "Spec %i", "%i", exp_buf, res_buf);

  s21_sprintf(res_buf, "%d", 12);
  sprintf(exp_buf, "%d", 12);
  check_and_print(&test_start_num, "Spec %i", "%i", exp_buf, res_buf);
  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_e) {
  int num_test = 1;
  test_float("%e", "Spec \"%e\"", &num_test);
}
END_TEST

START_TEST(test_spec_E) {
  int num_test = 1;
  test_float("%E", "Spec \"%E\"", &num_test);
}
END_TEST

START_TEST(test_spec_f) {
  int num_test = 1;
  test_float("%f", "Spec \"%f\"", &num_test);
}
END_TEST

START_TEST(test_spec_g) {
  int num_test = 1;
  test_float("%g", "Spec \"%g\"", &num_test);
}
END_TEST

START_TEST(test_spec_G) {
  int num_test = 1;
  test_float("%G", "Spec \"%G\"", &num_test);
}
END_TEST

START_TEST(test_spec_o) {
  unsigned int test_int, big_int, min_int;
  big_int = INT32_MAX;
  min_int = INT32_MIN;
  int test_start_num = 1;
  test_int = 100;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%o", test_int);
  sprintf(exp_buf, "%o", test_int);
  check_and_print(&test_start_num, "Spec %o", "%o", exp_buf, res_buf);

  s21_sprintf(res_buf, "%o", big_int);
  sprintf(exp_buf, "%o", big_int);
  check_and_print(&test_start_num, "Spec %o", "%o", exp_buf, res_buf);

  s21_sprintf(res_buf, "%o", min_int);
  sprintf(exp_buf, "%o", min_int);
  check_and_print(&test_start_num, "Spec %o", "%o", exp_buf, res_buf);

  test_int = -1;
  s21_sprintf(res_buf, "%o", min_int);
  sprintf(exp_buf, "%o", min_int);
  check_and_print(&test_start_num, "Spec %o", "%o", exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_s) {
  char* test_str = calloc(100, sizeof(char));
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));

  strcpy(test_str, "");

  s21_sprintf(res_buf, "%s", test_str);
  sprintf(exp_buf, "%s", test_str);
  ck_assert_msg(
      !strcmp(res_buf, exp_buf) && (strlen(res_buf) == strlen(exp_buf)),
      "\n\nERROR#1: specification "
      "\"%%s\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      exp_buf, res_buf);

  strcpy(test_str, "ABCDFPKDHJF0Likh;ajlhdsf;a ldf1230");

  s21_sprintf(res_buf, "%s", test_str);
  sprintf(exp_buf, "%s", test_str);
  ck_assert_msg(
      !strcmp(res_buf, exp_buf) && (strlen(res_buf) == strlen(exp_buf)),
      "\n\nERROR#2: specification "
      "\"%%s\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
      exp_buf, res_buf);
  free(res_buf);
  free(exp_buf);
  free(test_str);
}
END_TEST

START_TEST(test_spec_u) {
  int test_int, big_int, min_int, hex_num;
  big_int = INT32_MAX;
  min_int = INT32_MIN;
  test_int = 100;
  int test_start_num = 1;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%u", test_int);
  sprintf(exp_buf, "%u", test_int);
  check_and_print(&test_start_num, "Spec %u", "%u", exp_buf, res_buf);

  s21_sprintf(res_buf, "%u", big_int);
  sprintf(exp_buf, "%u", big_int);
  check_and_print(&test_start_num, "Spec %u", "%u", exp_buf, res_buf);

  s21_sprintf(res_buf, "%u", min_int);
  sprintf(exp_buf, "%u", min_int);
  check_and_print(&test_start_num, "Spec %u", "%u", exp_buf, res_buf);

  hex_num = 0xfa;
  s21_sprintf(res_buf, "%u", hex_num);
  sprintf(exp_buf, "%u", hex_num);
  check_and_print(&test_start_num, "Spec %u", "%u", exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_x) {
  int test_int, big_int, min_int, hex_num;
  big_int = INT32_MAX;
  min_int = INT32_MIN;
  test_int = 100;
  int test_start_num = 1;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%x", test_int);
  sprintf(exp_buf, "%x", test_int);
  check_and_print(&test_start_num, "Spec %x", "%x", exp_buf, res_buf);

  s21_sprintf(res_buf, "%x", big_int);
  sprintf(exp_buf, "%x", big_int);
  check_and_print(&test_start_num, "Spec %x", "%x", exp_buf, res_buf);

  s21_sprintf(res_buf, "%x", min_int);
  sprintf(exp_buf, "%x", min_int);
  check_and_print(&test_start_num, "Spec %x", "%x", exp_buf, res_buf);

  hex_num = 0xfa;
  s21_sprintf(res_buf, "%x", hex_num);
  sprintf(exp_buf, "%x", hex_num);
  check_and_print(&test_start_num, "Spec %x", "%x", exp_buf, res_buf);
  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_X) {
  int test_int, big_int, min_int, hex_num;
  big_int = INT32_MAX;
  min_int = INT32_MIN;
  test_int = 100;
  int test_start_num = 1;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%X", test_int);
  sprintf(exp_buf, "%X", test_int);
  check_and_print(&test_start_num, "Spec %X", "%X", exp_buf, res_buf);

  s21_sprintf(res_buf, "%X", big_int);
  sprintf(exp_buf, "%X", big_int);
  check_and_print(&test_start_num, "Spec %X", "%X", exp_buf, res_buf);

  s21_sprintf(res_buf, "%X", min_int);
  sprintf(exp_buf, "%X", min_int);
  check_and_print(&test_start_num, "Spec %X", "%X", exp_buf, res_buf);

  hex_num = 0xfa;
  s21_sprintf(res_buf, "%X", hex_num);
  sprintf(exp_buf, "%X", hex_num);
  check_and_print(&test_start_num, "Spec %X", "%X", exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_p) {
  int test_int;
  test_int = 100;
  int test_start_num = 1;
  char* res_buf = calloc(100, sizeof(char));
  char* exp_buf = calloc(100, sizeof(char));

  s21_sprintf(res_buf, "%p", (void*)&test_int);
  sprintf(exp_buf, "%p", (void*)&test_int);
  check_and_print(&test_start_num, "Spec %p", "%p", exp_buf, res_buf);

  s21_sprintf(res_buf, "%p", res_buf);
  sprintf(exp_buf, "%p", res_buf);
  check_and_print(&test_start_num, "Spec %p", "%p", exp_buf, res_buf);

  s21_sprintf(res_buf, "%p", exp_buf);
  sprintf(exp_buf, "%p", exp_buf);
  check_and_print(&test_start_num, "Spec %p", "%p", exp_buf, res_buf);

  s21_sprintf(res_buf, "%p", NULL);
  sprintf(exp_buf, "%p", NULL);
  check_and_print(&test_start_num, "Spec %p", "%p", exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_spec_n) {
  char* test_str = calloc(100, sizeof(char));
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));
  int res_how_much, exp_how_much;

  strcpy(test_str, "123456789");
  s21_sprintf(res_buf, "%s %n", test_str, &res_how_much);
  sprintf(exp_buf, "%s %n", test_str, &exp_how_much);
  ck_assert_msg(res_how_much == exp_how_much,
                "\n\nERROR#1: specification "
                "\"%%n\"\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n",
                exp_how_much, res_how_much);

  strcpy(test_str, "");
  s21_sprintf(res_buf, "%s%n", test_str, &res_how_much);
  sprintf(exp_buf, "%s%n", test_str, &exp_how_much);
  ck_assert_msg(res_how_much == exp_how_much,
                "\n\nERROR#2: specification "
                "\"%%n\"\nEXCEPTED_VALUE=(%d)\nRESULT_VALUE=(%d)\n",
                exp_how_much, res_how_much);

  free(res_buf);
  free(exp_buf);
  free(test_str);
}
END_TEST

START_TEST(test_spec_PERCENT) {
  char* test_str = calloc(100, sizeof(char));
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));

  strcpy(test_str, "123456789");

  s21_sprintf(res_buf, "%%");
  sprintf(exp_buf, "%%");

  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#1: specification "
                "\"%%\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  strcpy(test_str, "");

  s21_sprintf(res_buf, "%% %%");
  sprintf(exp_buf, "%% %%");

  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#2: specification "
                "\"%%\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);
  free(res_buf);
  free(exp_buf);
  free(test_str);
}
END_TEST

//
// ======= TEST WEIGHT ======
//

START_TEST(test_size_weight) {
  int test_num = 1;
  for_flag_specification("10", "Test weight(10)", &test_num);
  for_flag_specification("30", "Test weight(30)", &test_num);
}
END_TEST

START_TEST(test_size_weight_arg) {
  char* test_str = calloc(100, sizeof(char));
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));
  int test_int;
  strcpy(test_str, "adsfsadfas");

  s21_sprintf(res_buf, "%*s", 25, test_str);
  sprintf(exp_buf, "%*s", 25, test_str);
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#1: weight "
                "spec.\"%%s\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",

                exp_buf, res_buf);

  test_int = 11230128;

  s21_sprintf(res_buf, "%*d", 20, test_int);
  sprintf(exp_buf, "%*d", 20, test_int);
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#2: weight spec. "
                "\"%%d\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  s21_sprintf(res_buf, "%*d %*s", 20, test_int, 30, test_str);
  sprintf(exp_buf, "%*d %*s", 20, test_int, 30, test_str);
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#3: weight spec. \"%%d "
                "%%s\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  s21_sprintf(res_buf, "%*p", 20, NULL);
  sprintf(exp_buf, "%*p", 20, NULL);
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#4: weight spec. "
                "\"%%p\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  s21_sprintf(res_buf, "%*p", 20, test_str);
  sprintf(exp_buf, "%*p", 20, test_str);
  ck_assert_msg(!strcmp(res_buf, exp_buf),
                "\n\nERROR#5: weight spec. "
                "\"%%p\"\nEXCEPTED_VALUE=(%s)\nRESULT_VALUE=(%s)\n",
                exp_buf, res_buf);

  free(res_buf);
  free(exp_buf);
  free(test_str);
}
END_TEST

//
// ======= TEST FLAGS ======
//
START_TEST(test_flag_minus) {
  int test_num = 1;
  for_flag_specification("-", "Test minus", &test_num);
  for_flag_specification("-30", "Test minus width", &test_num);
}
END_TEST

START_TEST(test_flag_plus) {
  int test_num = 1;
  for_flag_specification("+", "Test plus", &test_num);
  for_flag_specification("+10", "Test plus with width", &test_num);
}
END_TEST

START_TEST(test_flag_space) {
  int test_num = 1;
  for_flag_specification(" ", "Test space", &test_num);
  for_flag_specification(" 10", "Test space with width", &test_num);
}
END_TEST

START_TEST(test_flag_octothorpe) {
  int num_test = 1;
  for_flag_specification("#", "Test octothorpe", &num_test);
  for_flag_specification("#10", "Test octothorpe", &num_test);
}
END_TEST

START_TEST(test_flag_zero) {
  int test_num = 1;
  for_flag_specification("010", "Test zero", &test_num);
}
END_TEST

START_TEST(test_flags) {
  int test_num = 1;
  char* flag_spec = (char*)calloc(10, sizeof(char));
  char* flags[] = {"-", "+", " ", "#", "0"};

  for (int i = 0; i < 5; i++) {
    for (int j = 0; j < 5; j++) {
      if (i != j) {
        memset(flag_spec, 0, 10);
        strcpy(flag_spec, flags[i]);
        strcpy(flag_spec + 1, flags[j]);
        for_flag_specification(flag_spec, "Test \'-+\"", &test_num);

        strcpy(flag_spec + 2, "10");
        for_flag_specification(flag_spec, "Test \'-+\"", &test_num);
      }
    }
  }
}
END_TEST

//================================================================
//=======================ACCURACY=================================
//================================================================

START_TEST(test_accurate) {
  int test_num = 1;
  for_flag_specification(".2", "Test accurate (.2)", &test_num);
  for_flag_specification(".10", "Test accurate (.10)", &test_num);
  for_flag_specification(".12", "Test accurate (.12)", &test_num);
  for_flag_specification_wtih_star(".*", "Test accurate with * (.2)", &test_num,
                                   2);
  for_flag_specification_wtih_star(".*", "Test accurate with * (.12)",
                                   &test_num, 12);
}
END_TEST

//================================================================
//=======================LONG=================================
//================================================================

START_TEST(test_long) {
  int test_num = 1;
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));
  char* specification_str = calloc(120, sizeof(char));
  char name_spec[] = "Test long (h)";

  char* test_1[] = {"d", "i", "o", "u", "x", "X"};
  char* current_format = "h";
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, INT32_MAX);
    sprintf(exp_buf, specification_str, INT32_MAX);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, INT32_MIN);
    sprintf(exp_buf, specification_str, INT32_MIN);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format, test_1[i]);
    s21_sprintf(res_buf, specification_str, 12);
    sprintf(exp_buf, specification_str, 12);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);
  }

  char* current_format2 = "l";
  char name_spec2[] = "Test long (l)";
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format2, test_1[i]);
    s21_sprintf(res_buf, specification_str, 0);
    sprintf(exp_buf, specification_str, 0);
    check_and_print(&test_num, name_spec2, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format2, test_1[i]);
    s21_sprintf(res_buf, specification_str, INT64_MAX);
    sprintf(exp_buf, specification_str, INT64_MAX);
    check_and_print(&test_num, name_spec2, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format2, test_1[i]);
    s21_sprintf(res_buf, specification_str, INT32_MIN);
    sprintf(exp_buf, specification_str, INT32_MIN);
    check_and_print(&test_num, name_spec2, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format2, test_1[i]);
    s21_sprintf(res_buf, specification_str, INT64_MIN);
    sprintf(exp_buf, specification_str, INT64_MIN);
    check_and_print(&test_num, name_spec2, specification_str, exp_buf, res_buf);
  }

  check_and_print(&test_num, name_spec2, specification_str, exp_buf, res_buf);

  free(specification_str);
  free(res_buf);
  free(exp_buf);
}
END_TEST

START_TEST(test_long_double) {
  int test_num = 1;
  char* exp_buf = calloc(120, sizeof(char));
  char* res_buf = calloc(120, sizeof(char));
  char* specification_str = calloc(120, sizeof(char));
  char name_spec[] = "Test long double";

  char* test_2[] = {"e", "E", "f", "g", "G"};
  char* current_format = "L";
  long double ld_1 = 5.32e-5;
  long double ld_2 = -1231241214;
  long double ld_3 = 1. / 3.;
  long double ld_4 = 0.;
  for (int i = 0; i < 5; i++) {
    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, ld_1);
    sprintf(exp_buf, specification_str, ld_1);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, ld_2);
    sprintf(exp_buf, specification_str, ld_2);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, ld_3);
    sprintf(exp_buf, specification_str, ld_3);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);

    enter_specification(specification_str, current_format, test_2[i]);
    s21_sprintf(res_buf, specification_str, ld_4);
    sprintf(exp_buf, specification_str, ld_4);
    check_and_print(&test_num, name_spec, specification_str, exp_buf, res_buf);
  }

  free(res_buf);
  free(exp_buf);
  free(specification_str);
}
END_TEST

//========================================================
//========================================================

int main(void) {
  Suite* s1 = suite_create("Core");
  TCase* tc1_1 = tcase_create("Core");
  SRunner* sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_s21_memchr);
  tcase_add_test(tc1_1, test_s21_memcmp);
  tcase_add_test(tc1_1, test_s21_strcmp);
  tcase_add_test(tc1_1, test_s21_memcpy);
  tcase_add_test(tc1_1, test_s21_memmove);
  tcase_add_test(tc1_1, test_s21_memset);
  tcase_add_test(tc1_1, test_s21_strcat);
  tcase_add_test(tc1_1, test_s21_strncat);
  tcase_add_test(tc1_1, test_s21_strchr);
  tcase_add_test(tc1_1, test_s21_strncmp);
  tcase_add_test(tc1_1, test_s21_strcpy);
  tcase_add_test(tc1_1, test_s21_strncpy);
  tcase_add_test(tc1_1, test_strcspn);
  tcase_add_test(tc1_1, test_strerror);
  tcase_add_test(tc1_1, test_strlen);
  tcase_add_test(tc1_1, test_strpbrk);
  tcase_add_test(tc1_1, test_strrchr);
  tcase_add_test(tc1_1, test_strspn);
  tcase_add_test(tc1_1, test_strstr);
  tcase_add_test(tc1_1, test_strtok);
  tcase_add_test(tc1_1, test_to_upper);
  tcase_add_test(tc1_1, test_to_lower);
  tcase_add_test(tc1_1, test_insert);
  tcase_add_test(tc1_1, test_trim);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_d);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_c);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_s);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_i);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_eEfgG);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_ouxX);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_p);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_n);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_percent);
  tcase_add_test(tc1_1, test_s21_sscanf_spec_combination);

  tcase_add_test(tc1_1, test_spec_c);
  tcase_add_test(tc1_1, test_spec_d);
  tcase_add_test(tc1_1, test_spec_i);
  tcase_add_test(tc1_1, test_spec_e);
  tcase_add_test(tc1_1, test_spec_E);
  tcase_add_test(tc1_1, test_spec_f);
  tcase_add_test(tc1_1, test_spec_g);
  tcase_add_test(tc1_1, test_spec_G);
  tcase_add_test(tc1_1, test_spec_o);
  tcase_add_test(tc1_1, test_spec_s);
  tcase_add_test(tc1_1, test_spec_u);
  tcase_add_test(tc1_1, test_spec_x);
  tcase_add_test(tc1_1, test_spec_X);
  tcase_add_test(tc1_1, test_spec_p);
  tcase_add_test(tc1_1, test_spec_n);
  tcase_add_test(tc1_1, test_spec_PERCENT);
  tcase_add_test(tc1_1, test_size_weight);
  tcase_add_test(tc1_1, test_size_weight_arg);
  tcase_add_test(tc1_1, test_flag_minus);
  tcase_add_test(tc1_1, test_flag_plus);
  tcase_add_test(tc1_1, test_flag_space);
  tcase_add_test(tc1_1, test_flag_octothorpe);
  tcase_add_test(tc1_1, test_flag_zero);
  tcase_add_test(tc1_1, test_flags);
  tcase_add_test(tc1_1, test_accurate);
  tcase_add_test(tc1_1, test_long);
  tcase_add_test(tc1_1, test_long_double);
  tcase_add_test(tc1_1, DIMON);
  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
  // return 0;
}
